provinces_data = [
    {"id": "1", "name_uz": "Qoraqalpogʻiston Respublikasi", "name_oz": "Қорақалпоғистон Республикаси",
     "name_ru": "Республика Каракалпакстан", "name_en": "Republic of Karakalpakstan"},
    {"id": "2", "name_uz": "Andijon viloyati", "name_oz": "Андижон вилояти", "name_ru": "Андижанская область",
     "name_en": "Andijan Region"},
    {"id": "3", "name_uz": "Buxoro viloyati", "name_oz": "Бухоро вилояти", "name_ru": "Бухарская область",
     "name_en": "Bukhara Region"},
    {"id": "4", "name_uz": "Jizzax viloyati", "name_oz": "Жиззах вилояти", "name_ru": "Джизакская область",
     "name_en": "Jizzakh Region"},
    {"id": "5", "name_uz": "Qashqadaryo viloyati", "name_oz": "Қашқадарё вилояти", "name_ru": "Кашкадарьинская область",
     "name_en": "Qashqadaryo Region"},
    {"id": "6", "name_uz": "Navoiy viloyati", "name_oz": "Навоий вилояти", "name_ru": "Навоийская область",
     "name_en": "Navoi Region"},
    {"id": "7", "name_uz": "Namangan viloyati", "name_oz": "Наманган вилояти", "name_ru": "Наманганская область",
     "name_en": "Namangan Region"},
    {"id": "8", "name_uz": "Samarqand viloyati", "name_oz": "Самарқанд вилояти", "name_ru": "Самаркандская область",
     "name_en": "Samarkand Region"},
    {"id": "9", "name_uz": "Surxondaryo viloyati", "name_oz": "Сурхондарё вилояти",
     "name_ru": "Сурхандарьинская область", "name_en": "Surxondaryo Region"},
    {"id": "10", "name_uz": "Sirdaryo viloyati", "name_oz": "Сирдарё вилояти", "name_ru": "Сырдарьинская область",
     "name_en": "Sirdaryo Region"},
    {"id": "11", "name_uz": "Toshkent viloyati", "name_oz": "Тошкент вилояти", "name_ru": "Ташкентская область",
     "name_en": "Tashkent Region"},
    {"id": "12", "name_uz": "Fargʻona viloyati", "name_oz": "Фарғона вилояти", "name_ru": "Ферганская область",
     "name_en": "Fergana Region"},
    {"id": "13", "name_uz": "Xorazm viloyati", "name_oz": "Хоразм вилояти", "name_ru": "Хорезмская область",
     "name_en": "Khorezm Region"},
    {"id": "14", "name_uz": "Toshkent shahri", "name_oz": "Тошкент шаҳри", "name_ru": "Город Ташкент",
     "name_en": "City of Tashkent"}
]

districts_data = [
    {'id': 15, 'province_id': 1, 'name_uz': 'Amudaryo tumani', 'name_cyrillic': 'Амударё тумани',
     'name_ru': 'Амударьинский район', 'name_en': 'Amudaryo district'},
    {'id': 16, 'province_id': 1, 'name_uz': 'Beruniy tumani', 'name_cyrillic': 'Беруний тумани',
     'name_ru': 'Берунийский район', 'name_en': 'Beruniy district'},
    {'id': 17, 'province_id': 1, 'name_uz': 'Kegayli tumani', 'name_cyrillic': 'Кегайли тумани',
     'name_ru': 'Кегейлийский район', 'name_en': 'Kegayli district'},
    {'id': 18, 'province_id': 1, 'name_uz': 'Qonliko‘l tumani', 'name_cyrillic': 'Қонликўл тумани',
     'name_ru': 'Канлыкульский район', 'name_en': 'Qonliko‘l district'},
    {'id': 19, 'province_id': 1, 'name_uz': 'Qorao‘zak tumani', 'name_cyrillic': 'Қораўзак тумани',
     'name_ru': 'Караузякский район', 'name_en': 'Qorao‘zak district'},
    {'id': 20, 'province_id': 1, 'name_uz': 'Qo‘ng‘irot tumani', 'name_cyrillic': 'Қўнғирот тумани',
     'name_ru': 'Кунградский район', 'name_en': 'Qo‘ng‘irot district'},
    {'id': 21, 'province_id': 1, 'name_uz': 'Mo‘ynoq tumani', 'name_cyrillic': 'Мўйноқ тумани',
     'name_ru': 'Муйнакский район', 'name_en': 'Mo‘ynoq district'},
    {'id': 22, 'province_id': 1, 'name_uz': 'Nukus tumani', 'name_cyrillic': 'Нукус тумани',
     'name_ru': 'Нукусский район', 'name_en': 'Nukus district'},
    {'id': 23, 'province_id': 1, 'name_uz': 'Nukus shahri', 'name_cyrillic': 'Нукус шаҳри', 'name_ru': 'город Нукус',
     'name_en': 'Nukus city'},
    {'id': 24, 'province_id': 1, 'name_uz': 'Taxtako‘pir tumani', 'name_cyrillic': 'Тахтакўпир тумани',
     'name_ru': 'Тахтакупырский район', 'name_en': 'Taxtako‘pir district'},
    {'id': 25, 'province_id': 1, 'name_uz': 'To‘rtko‘l tumani', 'name_cyrillic': 'Тўрткўл тумани',
     'name_ru': 'Турткульский район', 'name_en': 'To‘rtko‘l district'},
    {'id': 26, 'province_id': 1, 'name_uz': 'Xo‘jayli tumani', 'name_cyrillic': 'Хўжайли тумани',
     'name_ru': 'Ходжейлийский район', 'name_en': 'Xo‘jayli district'},
    {'id': 27, 'province_id': 1, 'name_uz': 'Chimboy tumani', 'name_cyrillic': 'Чимбой тумани',
     'name_ru': 'Чимбайский район', 'name_en': 'Chimboy district'},
    {'id': 28, 'province_id': 1, 'name_uz': 'Shumanay tumani', 'name_cyrillic': 'Шуманай тумани',
     'name_ru': 'Шуманайский район', 'name_en': 'Shumanay district'},
    {'id': 29, 'province_id': 1, 'name_uz': 'Ellikqal‘a tumani', 'name_cyrillic': 'Элликқалъа тумани',
     'name_ru': 'Элликкалинский район', 'name_en': 'Ellikqal‘a district'},
    {'id': 30, 'province_id': 2, 'name_uz': 'Andijon shahri', 'name_cyrillic': 'Андижон шаҳри',
     'name_ru': 'город Андижан', 'name_en': 'Andijon city'},
    {'id': 31, 'province_id': 2, 'name_uz': 'Andijon tumani', 'name_cyrillic': 'Андижон тумани',
     'name_ru': 'Андижанский район', 'name_en': 'Andijon district'},
    {'id': 32, 'province_id': 2, 'name_uz': 'Asaka tumani', 'name_cyrillic': 'Асака тумани',
     'name_ru': 'Асакинский район', 'name_en': 'Asaka district'},
    {'id': 33, 'province_id': 2, 'name_uz': 'Baliqchi tumani', 'name_cyrillic': 'Балиқчи тумани',
     'name_ru': 'Балыкчинский район', 'name_en': 'Baliqchi district'},
    {'id': 34, 'province_id': 2, 'name_uz': 'Buloqboshi tumani', 'name_cyrillic': 'Булоқбоши тумани',
     'name_ru': 'Булакбашинский район', 'name_en': 'Buloqboshi district'},
    {'id': 35, 'province_id': 2, 'name_uz': 'Bo‘z tumani', 'name_cyrillic': 'Бўз тумани', 'name_ru': 'Бозский район',
     'name_en': 'Bo‘z district'},
    {'id': 36, 'province_id': 2, 'name_uz': 'Jalaquduq tumani', 'name_cyrillic': 'Жалақудуқ тумани',
     'name_ru': 'Джалакудукский район', 'name_en': 'Jalaquduq district'},
    {'id': 37, 'province_id': 2, 'name_uz': 'Izbosgan tumani', 'name_cyrillic': 'Избосган тумани',
     'name_ru': 'Избасканский район', 'name_en': 'Izbosgan district'},
    {'id': 38, 'province_id': 2, 'name_uz': 'Qorasuv shahri', 'name_cyrillic': 'Қорасув шаҳри',
     'name_ru': 'город Карасув', 'name_en': 'Qorasuv city'},
    {'id': 39, 'province_id': 2, 'name_uz': 'Qo‘rg‘ontepa tumani', 'name_cyrillic': 'Қўрғонтепа тумани',
     'name_ru': 'Кургантепинский район', 'name_en': 'Qo‘rg‘ontepa district'},
    {'id': 40, 'province_id': 2, 'name_uz': 'Marhamat tumani', 'name_cyrillic': 'Марҳамат тумани',
     'name_ru': 'Мархаматский район', 'name_en': 'Marhamat district'},
    {'id': 41, 'province_id': 2, 'name_uz': 'Oltinko‘l tumani', 'name_cyrillic': 'Олтинкўл тумани',
     'name_ru': 'Алтынкульский район', 'name_en': 'Oltinko‘l district'},
    {'id': 42, 'province_id': 2, 'name_uz': 'Paxtaobod tumani', 'name_cyrillic': 'Пахтаобод тумани',
     'name_ru': 'Пахтаабадский район', 'name_en': 'Paxtaobod district'},
    {'id': 43, 'province_id': 2, 'name_uz': 'Ulug‘nor tumani', 'name_cyrillic': 'Улуғнор тумани',
     'name_ru': 'Улугнорский район', 'name_en': 'Ulug‘nor district'},
    {'id': 44, 'province_id': 2, 'name_uz': 'Xonabod tumani', 'name_cyrillic': 'Хонабод тумани',
     'name_ru': 'город Ханабад', 'name_en': 'Xonabod city'},
    {'id': 45, 'province_id': 2, 'name_uz': 'Xo‘jaobod tumani', 'name_cyrillic': 'Хўжаобод тумани',
     'name_ru': 'Ходжаабадский район', 'name_en': 'Xo‘jaobod district'},
    {'id': 46, 'province_id': 2, 'name_uz': 'Shahrixon tumani', 'name_cyrillic': 'Шаҳрихон тумани',
     'name_ru': 'Шахриханский район', 'name_en': 'Shahrixon district'},
    {'id': 47, 'province_id': 3, 'name_uz': 'Buxoro shahri', 'name_cyrillic': 'Бухоро шаҳри', 'name_ru': 'город Бухара',
     'name_en': 'Bukhara city'},
    {'id': 48, 'province_id': 3, 'name_uz': 'Buxoro tumani', 'name_cyrillic': 'Бухоро тумани',
     'name_ru': 'Бухарский район', 'name_en': 'Bukhara district'},
    {'id': 49, 'province_id': 3, 'name_uz': 'Vobkent tumani', 'name_cyrillic': 'Вобкент тумани',
     'name_ru': 'Вабкентский район', 'name_en': 'Vobkent district'},
    {'id': 50, 'province_id': 3, 'name_uz': 'G‘ijduvon tumani', 'name_cyrillic': 'Ғиждувон тумани',
     'name_ru': 'Гиждуванский район', 'name_en': 'G‘ijduvon district'},
    {'id': 51, 'province_id': 3, 'name_uz': 'Jondor tumani', 'name_cyrillic': 'Жондор тумани',
     'name_ru': 'Жондорский район', 'name_en': 'Jondor district'},
    {'id': 52, 'province_id': 3, 'name_uz': 'Kogon tumani', 'name_cyrillic': 'Когон тумани',
     'name_ru': 'Каганский район', 'name_en': 'Kogon district'},
    {'id': 53, 'province_id': 3, 'name_uz': 'Kogon shahri', 'name_cyrillic': 'Когон шаҳри', 'name_ru': 'город Каган',
     'name_en': 'Kogon city'},
    {'id': 54, 'province_id': 3, 'name_uz': 'Qorako‘l tumani', 'name_cyrillic': 'Қоракўл тумани',
     'name_ru': 'Каракульский район', 'name_en': 'Qorako‘l district'},
    {'id': 55, 'province_id': 3, 'name_uz': 'Qorovulbozor tumani', 'name_cyrillic': 'Қоровулбозор тумани',
     'name_ru': 'Караулбазарский район', 'name_en': 'Qorovulbozor district'},
    {'id': 56, 'province_id': 3, 'name_uz': 'Olot tumani', 'name_cyrillic': 'Олот тумани', 'name_ru': 'Алатский район',
     'name_en': 'Olot district'},
    {'id': 57, 'province_id': 3, 'name_uz': 'Peshku tumani', 'name_cyrillic': 'Пешку тумани',
     'name_ru': 'Пешкунский район', 'name_en': 'Peshku district'},
    {'id': 58, 'province_id': 3, 'name_uz': 'Romitan tumani', 'name_cyrillic': 'Ромитан тумани',
     'name_ru': 'Ромитанский район', 'name_en': 'Romitan district'},
    {'id': 59, 'province_id': 3, 'name_uz': 'Shofirkon tumani', 'name_cyrillic': 'Шофиркон тумани',
     'name_ru': 'Шафирканский район', 'name_en': 'Shofirkon district'},
    {'id': 60, 'province_id': 4, 'name_uz': 'Arnasoy tumani', 'name_cyrillic': 'Арнасой тумани',
     'name_ru': 'Арнасайский район', 'name_en': 'Arnasoy district'},
    {'id': 61, 'province_id': 4, 'name_uz': 'Baxmal tumani', 'name_cyrillic': 'Бахмал тумани',
     'name_ru': 'Бахмальский район', 'name_en': 'Baxmal district'},
    {'id': 62, 'province_id': 4, 'name_uz': 'G‘allaorol tumani', 'name_cyrillic': 'Ғаллаорол тумани',
     'name_ru': 'Галляаральский район', 'name_en': 'G‘allaorol district'},
    {'id': 63, 'province_id': 4, 'name_uz': 'Do‘stlik tumani', 'name_cyrillic': 'Дўстлик тумани',
     'name_ru': 'Дустликский район', 'name_en': 'Do‘stlik district'},
    {'id': 64, 'province_id': 4, 'name_uz': 'Sh.Rashidov tumani', 'name_cyrillic': 'Ш.Рашидов тумани',
     'name_ru': 'Шараф-Рашидовский район', 'name_en': 'Sh.Rashidov district'},
    {'id': 65, 'province_id': 4, 'name_uz': 'Jizzax shahri', 'name_cyrillic': 'Жиззах шаҳри', 'name_ru': 'город Джизак',
     'name_en': 'Jizzax city'},
    {'id': 66, 'province_id': 4, 'name_uz': 'Zarbdor tumani', 'name_cyrillic': 'Зарбдор тумани',
     'name_ru': 'Зарбдарский район', 'name_en': 'Zarbdor district'},
    {'id': 67, 'province_id': 4, 'name_uz': 'Zafarobod tumani', 'name_cyrillic': 'Зафаробод тумани',
     'name_ru': 'Зафарабадский район', 'name_en': 'Zafarobod district'},
    {'id': 68, 'province_id': 4, 'name_uz': 'Zomin tumani', 'name_cyrillic': 'Зомин тумани',
     'name_ru': 'Зааминский район', 'name_en': 'Zomin district'},
    {'id': 69, 'province_id': 4, 'name_uz': 'Mirzacho‘l tumani', 'name_cyrillic': 'Мирзачўл тумани',
     'name_ru': 'Мирзачульский район', 'name_en': 'Mirzacho‘l district'},
    {'id': 70, 'province_id': 4, 'name_uz': 'Paxtakor tumani', 'name_cyrillic': 'Пахтакор тумани',
     'name_ru': 'Пахтакорский район', 'name_en': 'Paxtakor district'},
    {'id': 71, 'province_id': 4, 'name_uz': 'Forish tumani', 'name_cyrillic': 'Фориш тумани',
     'name_ru': 'Фаришский район', 'name_en': 'Forish district'},
    {'id': 72, 'province_id': 4, 'name_uz': 'Yangiobod tumani', 'name_cyrillic': 'Янгиобод тумани',
     'name_ru': 'Янгиабадский район', 'name_en': 'Yangiobod district'},
    {'id': 73, 'province_id': 5, 'name_uz': 'G‘uzor tumani', 'name_cyrillic': 'Ғузор тумани',
     'name_ru': 'Гузарский район', 'name_en': 'G‘uzor district'},
    {'id': 74, 'province_id': 5, 'name_uz': 'Dehqonobod tumani', 'name_cyrillic': 'Деҳқонобод тумани',
     'name_ru': 'Дехканабадский район', 'name_en': 'Dehqonobod district'},
    {'id': 75, 'province_id': 5, 'name_uz': 'Qamashi tumani', 'name_cyrillic': 'Қамаши тумани',
     'name_ru': 'Камашинский район', 'name_en': 'Qamashi district'},
    {'id': 76, 'province_id': 5, 'name_uz': 'Qarshi tumani', 'name_cyrillic': 'Қарши тумани',
     'name_ru': 'Каршинский район', 'name_en': 'Qarshi district'},
    {'id': 77, 'province_id': 5, 'name_uz': 'Qarshi shahri', 'name_cyrillic': 'Қарши шаҳри', 'name_ru': 'город Карши',
     'name_en': 'Qarshi city'},
    {'id': 78, 'province_id': 5, 'name_uz': 'Kasbi tumani', 'name_cyrillic': 'Касби тумани',
     'name_ru': 'Касбийский район', 'name_en': 'Kasbi district'},
    {'id': 79, 'province_id': 5, 'name_uz': 'Kitob tumani', 'name_cyrillic': 'Китоб тумани',
     'name_ru': 'Китабский район', 'name_en': 'Kitob district'},
    {'id': 80, 'province_id': 5, 'name_uz': 'Koson tumani', 'name_cyrillic': 'Косон тумани',
     'name_ru': 'Касанский район', 'name_en': 'Koson district'},
    {'id': 81, 'province_id': 5, 'name_uz': 'Mirishkor tumani', 'name_cyrillic': 'Миришкор тумани',
     'name_ru': 'Миришкорский район', 'name_en': 'Mirishkor district'},
    {'id': 82, 'province_id': 5, 'name_uz': 'Muborak tumani', 'name_cyrillic': 'Муборак тумани',
     'name_ru': 'Мубарекский район', 'name_en': 'Muborak district'},
    {'id': 83, 'province_id': 5, 'name_uz': 'Nishon tumani', 'name_cyrillic': 'Нишон тумани',
     'name_ru': 'Нишанский район', 'name_en': 'Nishon district'},
    {'id': 84, 'province_id': 5, 'name_uz': 'Chiroqchi tumani', 'name_cyrillic': 'Чироқчи тумани',
     'name_ru': 'Чиракчинский район', 'name_en': 'Chiroqchi district'},
    {'id': 85, 'province_id': 5, 'name_uz': 'Shahrisabz tumani', 'name_cyrillic': 'Шаҳрисабз тумани',
     'name_ru': 'Шахрисабзский район', 'name_en': 'Shahrisabz district'},
    {'id': 86, 'province_id': 5, 'name_uz': 'Yakkabog‘ tumani', 'name_cyrillic': 'Яккабоғ тумани',
     'name_ru': 'Яккабагский район', 'name_en': 'Yakkabog‘ district'},
    {'id': 87, 'province_id': 6, 'name_uz': 'Zarafshon shahri', 'name_cyrillic': 'Зарафшон шаҳри',
     'name_ru': 'город Зарафшан', 'name_en': 'Zarafshon city'},
    {'id': 88, 'province_id': 6, 'name_uz': 'Karmana tumani', 'name_cyrillic': 'Кармана тумани',
     'name_ru': 'Карманинский район', 'name_en': 'Karmana district'},
    {'id': 89, 'province_id': 6, 'name_uz': 'Qiziltepa tumani', 'name_cyrillic': 'Қизилтепа тумани',
     'name_ru': 'Кызылтепинский район', 'name_en': 'Qiziltepa district'},
    {'id': 90, 'province_id': 6, 'name_uz': 'Konimex tumani', 'name_cyrillic': 'Конимех тумани',
     'name_ru': 'Канимехский район', 'name_en': 'Konimex district'},
    {'id': 91, 'province_id': 6, 'name_uz': 'Navbahor tumani', 'name_cyrillic': 'Навбаҳор тумани',
     'name_ru': 'Навбахорский район', 'name_en': 'Navbahor district'},
    {'id': 92, 'province_id': 6, 'name_uz': 'Navoiy shahri', 'name_cyrillic': 'Навоий шаҳри', 'name_ru': 'город Навои',
     'name_en': 'Navoiy city'},
    {'id': 93, 'province_id': 6, 'name_uz': 'Nurota tumani', 'name_cyrillic': 'Нурота тумани',
     'name_ru': 'Нуратинский район', 'name_en': 'Nurota district'},
    {'id': 94, 'province_id': 6, 'name_uz': 'Tomdi tumani', 'name_cyrillic': 'Томди тумани',
     'name_ru': 'Тамдынский район', 'name_en': 'Tomdi district'},
    {'id': 95, 'province_id': 6, 'name_uz': 'Uchquduq tumani', 'name_cyrillic': 'Учқудуқ тумани',
     'name_ru': 'Учкудукский район', 'name_en': 'Uchquduq district'},
    {'id': 96, 'province_id': 6, 'name_uz': 'Xatirchi tumani', 'name_cyrillic': 'Хатирчи тумани',
     'name_ru': 'Хатырчинский район', 'name_en': 'Xatirchi district'},
    {'id': 97, 'province_id': 7, 'name_uz': 'Kosonsoy tumani', 'name_cyrillic': 'Косонсой тумани',
     'name_ru': 'Касансайский район', 'name_en': 'Kosonsoy district'},
    {'id': 98, 'province_id': 7, 'name_uz': 'Mingbuloq tumani', 'name_cyrillic': 'Мингбулоқ тумани',
     'name_ru': 'Мингбулакский район', 'name_en': 'Mingbuloq district'},
    {'id': 99, 'province_id': 7, 'name_uz': 'Namangan tumani', 'name_cyrillic': 'Наманган тумани',
     'name_ru': 'Наманганский район', 'name_en': 'Namangan district'},
    {'id': 100, 'province_id': 7, 'name_uz': 'Namangan shahri', 'name_cyrillic': 'Наманган шаҳри',
     'name_ru': 'город Наманган', 'name_en': 'Namangan city'},
    {'id': 101, 'province_id': 7, 'name_uz': 'Norin tumani', 'name_cyrillic': 'Норин тумани',
     'name_ru': 'Нарынский район', 'name_en': 'Norin district'},
    {'id': 102, 'province_id': 7, 'name_uz': 'Pop tumani', 'name_cyrillic': 'Поп тумани', 'name_ru': 'Папский район',
     'name_en': 'Pop district'},
    {'id': 103, 'province_id': 7, 'name_uz': 'To‘raqo‘rg‘on tumani', 'name_cyrillic': 'Тўрақўрғон тумани',
     'name_ru': 'Туракурганский район', 'name_en': 'To‘raqo‘rg‘on district'},
    {'id': 104, 'province_id': 7, 'name_uz': 'Uychi tumani', 'name_cyrillic': 'Уйчи тумани',
     'name_ru': 'Уйчинский район', 'name_en': 'Uychi district'},
    {'id': 105, 'province_id': 7, 'name_uz': 'Uchqo‘rg‘on tumani', 'name_cyrillic': 'Учқўрғон тумани',
     'name_ru': 'Учкурганский район', 'name_en': 'Uchqo‘rg‘on district'},
    {'id': 106, 'province_id': 7, 'name_uz': 'Chortoq tumani', 'name_cyrillic': 'Чортоқ тумани',
     'name_ru': 'Чартакский район', 'name_en': 'Chortoq district'},
    {'id': 107, 'province_id': 7, 'name_uz': 'Chust tumani', 'name_cyrillic': 'Чуст тумани',
     'name_ru': 'Чустский район', 'name_en': 'Chust district'},
    {'id': 108, 'province_id': 7, 'name_uz': 'Yangiqo‘rg‘on tumani', 'name_cyrillic': 'Янгиқўрғон тумани',
     'name_ru': 'Янгикурганский район', 'name_en': 'Yangiqo‘rg‘on district'},
    {'id': 109, 'province_id': 8, 'name_uz': 'Bulung‘ur tumani', 'name_cyrillic': 'Булунғур тумани',
     'name_ru': 'Булунгурский район', 'name_en': 'Bulung‘ur district'},
    {'id': 110, 'province_id': 8, 'name_uz': 'Jomboy tumani', 'name_cyrillic': 'Жомбой тумани',
     'name_ru': 'Джамбайский район', 'name_en': 'Jomboy district'},
    {'id': 111, 'province_id': 8, 'name_uz': 'Ishtixon tumani', 'name_cyrillic': 'Иштихон тумани',
     'name_ru': 'Иштыханский район', 'name_en': 'Ishtixon district'},
    {'id': 112, 'province_id': 8, 'name_uz': 'Kattaqo‘rg‘on tumani', 'name_cyrillic': 'Каттақўрғон тумани',
     'name_ru': 'Каттакурганский район', 'name_en': 'Kattaqo‘rg‘on district'},
    {'id': 113, 'province_id': 8, 'name_uz': 'Kattaqo‘rg‘on shahri', 'name_cyrillic': 'Каттақўрғон шаҳри',
     'name_ru': 'город Каттакурган', 'name_en': 'Kattaqo‘rg‘on city'},
    {'id': 114, 'province_id': 8, 'name_uz': 'Qo‘shrabot tumani', 'name_cyrillic': 'Қўшработ тумани',
     'name_ru': 'Кошрабадский район', 'name_en': 'Qo‘shrabot district'},
    {'id': 115, 'province_id': 8, 'name_uz': 'Narpay tumani', 'name_cyrillic': 'Нарпай тумани',
     'name_ru': 'Нарпайский район', 'name_en': 'Narpay district'},
    {'id': 116, 'province_id': 8, 'name_uz': 'Nurabod tumani', 'name_cyrillic': 'Нурабод тумани',
     'name_ru': 'Нурабадский район', 'name_en': 'Nurabod district'},
    {'id': 117, 'province_id': 8, 'name_uz': 'Oqdaryo tumani', 'name_cyrillic': 'Оқдарё тумани',
     'name_ru': 'Акдарьинский район', 'name_en': 'Oqdaryo district'},
    {'id': 118, 'province_id': 8, 'name_uz': 'Payariq tumani', 'name_cyrillic': 'Паяриқ тумани',
     'name_ru': 'Пайарыкский район', 'name_en': 'Payariq district'},
    {'id': 119, 'province_id': 8, 'name_uz': 'Pastarg‘om tumani', 'name_cyrillic': 'Пастарғом тумани',
     'name_ru': 'Пастдаргомский район', 'name_en': 'Pastarg‘om district'},
    {'id': 120, 'province_id': 8, 'name_uz': 'Paxtachi tumani', 'name_cyrillic': 'Пахтачи тумани',
     'name_ru': 'Пахтачийский район', 'name_en': 'Paxtachi district'},
    {'id': 121, 'province_id': 8, 'name_uz': 'Samarqand tumani', 'name_cyrillic': 'Самарқанд тумани',
     'name_ru': 'Самаркандский район', 'name_en': 'Samarqand district'},
    {'id': 122, 'province_id': 8, 'name_uz': 'Samarqand shahri', 'name_cyrillic': 'Самарқанд шаҳри',
     'name_ru': 'город Самарканд', 'name_en': 'Samarqand city'},
    {'id': 123, 'province_id': 8, 'name_uz': 'Toyloq tumani', 'name_cyrillic': 'Тойлоқ тумани',
     'name_ru': 'Тайлакский район', 'name_en': 'Toyloq district'},
    {'id': 124, 'province_id': 8, 'name_uz': 'Urgut tumani', 'name_cyrillic': 'Ургут тумани',
     'name_ru': 'Ургутский район', 'name_en': 'Urgut district'},
    {'id': 125, 'province_id': 9, 'name_uz': 'Angor tumani', 'name_cyrillic': 'Ангор тумани',
     'name_ru': 'Ангорский район', 'name_en': 'Angor district'},
    {'id': 126, 'province_id': 9, 'name_uz': 'Boysun tumani', 'name_cyrillic': 'Бойсун тумани',
     'name_ru': 'Байсунский район', 'name_en': 'Boysun district'},
    {'id': 127, 'province_id': 9, 'name_uz': 'Denov tumani', 'name_cyrillic': 'Денов тумани',
     'name_ru': 'Денауский район', 'name_en': 'Denov district'},
    {'id': 128, 'province_id': 9, 'name_uz': 'Jarqo‘rg‘on tumani', 'name_cyrillic': 'Жарқўрғон тумани',
     'name_ru': 'Джаркурганский район', 'name_en': 'Jarqo‘rg‘on district'},
    {'id': 129, 'province_id': 9, 'name_uz': 'Qiziriq tumani', 'name_cyrillic': 'Қизириқ тумани',
     'name_ru': 'Кизирикский район', 'name_en': 'Qiziriq district'},
    {'id': 130, 'province_id': 9, 'name_uz': 'Qo‘mqo‘rg‘on tumani', 'name_cyrillic': 'Қўмқўрғон тумани',
     'name_ru': 'Кумкурганский район', 'name_en': 'Qo‘mqo‘rg‘on district'},
    {'id': 131, 'province_id': 9, 'name_uz': 'Muzrabot tumani', 'name_cyrillic': 'Музработ тумани',
     'name_ru': 'Музрабадский район', 'name_en': 'Muzrabot district'},
    {'id': 132, 'province_id': 9, 'name_uz': 'Oltinsoy tumani', 'name_cyrillic': 'Олтинсой тумани',
     'name_ru': 'Алтынсайский район', 'name_en': 'Oltinsoy district'},
    {'id': 133, 'province_id': 9, 'name_uz': 'Sariosiyo tumani', 'name_cyrillic': 'Сариосиё тумани',
     'name_ru': 'Сариасийский район', 'name_en': 'Sariosiyo district'},
    {'id': 134, 'province_id': 9, 'name_uz': 'Termiz tumani', 'name_cyrillic': 'Термиз тумани',
     'name_ru': 'Термезский район', 'name_en': 'Termiz district'},
    {'id': 135, 'province_id': 9, 'name_uz': 'Termiz shahri', 'name_cyrillic': 'Термиз шаҳри',
     'name_ru': 'город Термез', 'name_en': 'Termiz city'},
    {'id': 136, 'province_id': 9, 'name_uz': 'Uzun tumani', 'name_cyrillic': 'Узун тумани', 'name_ru': 'Узунский район',
     'name_en': 'Uzun district'},
    {'id': 137, 'province_id': 9, 'name_uz': 'Sherobod tumani', 'name_cyrillic': 'Шеробод тумани',
     'name_ru': 'Шерабадский район', 'name_en': 'Sherobod district'},
    {'id': 138, 'province_id': 9, 'name_uz': 'Sho‘rchi tumani', 'name_cyrillic': 'Шўрчи тумани',
     'name_ru': 'Шурчинский район', 'name_en': 'Sho‘rchi district'},
    {'id': 139, 'province_id': 10, 'name_uz': 'Boyovut tumani', 'name_cyrillic': 'Боёвут тумани',
     'name_ru': 'Баяутский район', 'name_en': 'Boyovut district'},
    {'id': 140, 'province_id': 10, 'name_uz': 'Guliston tumani', 'name_cyrillic': 'Гулистон тумани',
     'name_ru': 'Гулистанский район', 'name_en': 'Guliston district'},
    {'id': 141, 'province_id': 10, 'name_uz': 'Guliston shahri', 'name_cyrillic': 'Гулистон шаҳри',
     'name_ru': 'город Гулистан', 'name_en': 'Guliston city'},
    {'id': 142, 'province_id': 10, 'name_uz': 'Mirzaobod tumani', 'name_cyrillic': 'Мирзаобод тумани',
     'name_ru': 'Мирзаабадский район', 'name_en': 'Mirzaobod district'},
    {'id': 143, 'province_id': 10, 'name_uz': 'Oqoltin tumani', 'name_cyrillic': 'Оқолтин тумани',
     'name_ru': 'Акалтынский район', 'name_en': 'Oqoltin district'},
    {'id': 144, 'province_id': 10, 'name_uz': 'Sayxunobod tumani', 'name_cyrillic': 'Сайхунобод тумани',
     'name_ru': 'Сайхунабадский район', 'name_en': 'Sayxunobod district'},
    {'id': 145, 'province_id': 10, 'name_uz': 'Sardoba tumani', 'name_cyrillic': 'Сардоба тумани',
     'name_ru': 'Сардобский район', 'name_en': 'Sardoba district'},
    {'id': 146, 'province_id': 10, 'name_uz': 'Sirdaryo tumani', 'name_cyrillic': 'Сирдарё тумани',
     'name_ru': 'Сырдарьинский район', 'name_en': 'Sirdaryo district'},
    {'id': 147, 'province_id': 10, 'name_uz': 'Xavos tumani', 'name_cyrillic': 'Хавос тумани',
     'name_ru': 'Хавастский район', 'name_en': 'Xavos district'},
    {'id': 148, 'province_id': 10, 'name_uz': 'Shirin shahri', 'name_cyrillic': 'Ширин шаҳри', 'name_ru': 'город Ширин',
     'name_en': 'Shirin city'},
    {'id': 149, 'province_id': 10, 'name_uz': 'Yangiyer shahri', 'name_cyrillic': 'Янгиер шаҳри',
     'name_ru': 'город Янгиер', 'name_en': 'Yangiyer city'},
    {'id': 150, 'province_id': 11, 'name_uz': 'Angiren shahri', 'name_cyrillic': 'Ангирен шаҳри',
     'name_ru': 'город Ангрен', 'name_en': 'Angren city'},
    {'id': 151, 'province_id': 11, 'name_uz': 'Bekabod tumani', 'name_cyrillic': 'Бекабод тумани',
     'name_ru': 'Бекабадский район', 'name_en': 'Bekabod district'},
    {'id': 152, 'province_id': 11, 'name_uz': 'Bekabod shahri', 'name_cyrillic': 'Бекабод шаҳри',
     'name_ru': 'город Бекабад', 'name_en': 'Bekabod city'},
    {'id': 153, 'province_id': 11, 'name_uz': 'Bo‘ka tumani', 'name_cyrillic': 'Бўка тумани',
     'name_ru': 'Букинский район', 'name_en': 'Bo‘ka district'},
    {'id': 154, 'province_id': 11, 'name_uz': 'Bo‘stonliq tumani', 'name_cyrillic': 'Бўстонлиқ тумани',
     'name_ru': 'Бостанлыкский район', 'name_en': 'Bo‘stonliq district'},
    {'id': 155, 'province_id': 11, 'name_uz': 'Zangiota tumani', 'name_cyrillic': 'Зангиота тумани',
     'name_ru': 'Зангиатинский район', 'name_en': 'Zangiota district'},
    {'id': 156, 'province_id': 11, 'name_uz': 'Qibray tumani', 'name_cyrillic': 'Қибрай тумани',
     'name_ru': 'Кибрайский район', 'name_en': 'Qibray district'},
    {'id': 157, 'province_id': 11, 'name_uz': 'Quyichirchiq tumani', 'name_cyrillic': 'Қуйичирчиқ тумани',
     'name_ru': 'Куйичирчикский район', 'name_en': 'Quyichirchiq district'},
    {'id': 158, 'province_id': 11, 'name_uz': 'Oqqo‘rg‘on tumani', 'name_cyrillic': 'Оққўрғон тумани',
     'name_ru': 'Аккурганский район', 'name_en': 'Oqqo‘rg‘on district'},
    {'id': 159, 'province_id': 11, 'name_uz': 'Olmaliq shahri', 'name_cyrillic': 'Олмалиқ шаҳри',
     'name_ru': 'город Алмалык', 'name_en': 'Olmaliq city'},
    {'id': 160, 'province_id': 11, 'name_uz': 'Ohangaron tumani', 'name_cyrillic': 'Оҳангарон тумани',
     'name_ru': 'Ахангаранский район', 'name_en': 'Ohangaron district'},
    {'id': 161, 'province_id': 11, 'name_uz': 'Parkent tumani', 'name_cyrillic': 'Паркент тумани',
     'name_ru': 'Паркентский район', 'name_en': 'Parkent district'},
    {'id': 162, 'province_id': 11, 'name_uz': 'Piskent tumani', 'name_cyrillic': 'Пискент тумани',
     'name_ru': 'Пскентский район', 'name_en': 'Piskent district'},
    {'id': 163, 'province_id': 11, 'name_uz': 'O‘rtachirchiq tumani', 'name_cyrillic': 'Ўртачирчиқ тумани',
     'name_ru': 'Уртачирчикский район', 'name_en': 'O‘rtachirchiq district'},
    {'id': 164, 'province_id': 11, 'name_uz': 'Chinoz tumani', 'name_cyrillic': 'Чиноз тумани',
     'name_ru': 'Чиназский район', 'name_en': 'Chinoz district'},
    {'id': 165, 'province_id': 11, 'name_uz': 'Chirchiq shahri', 'name_cyrillic': 'Чирчиқ шаҳри',
     'name_ru': 'город Чирчик', 'name_en': 'Chirchiq city'},
    {'id': 166, 'province_id': 11, 'name_uz': 'Yuqorichirchiq tumani', 'name_cyrillic': 'Юқоричирчиқ тумани',
     'name_ru': 'Юкоричирчикский район', 'name_en': 'Yuqorichirchiq district'},
    {'id': 167, 'province_id': 11, 'name_uz': 'Yangiyo‘l tumani', 'name_cyrillic': 'Янгийўл тумани',
     'name_ru': 'Янгиюльский район', 'name_en': 'Yangiyo‘l district'},
    {'id': 168, 'province_id': 12, 'name_uz': 'Beshariq tumani', 'name_cyrillic': 'Бешариқ тумани',
     'name_ru': 'Бешарыкский район', 'name_en': 'Beshariq district'},
    {'id': 169, 'province_id': 12, 'name_uz': 'Bog‘dod tumani', 'name_cyrillic': 'Боғдод тумани',
     'name_ru': 'Багдадский район', 'name_en': 'Bog‘dod district'},
    {'id': 170, 'province_id': 12, 'name_uz': 'Buvayda tumani', 'name_cyrillic': 'Бувайда тумани',
     'name_ru': 'Бувайдинский район', 'name_en': 'Buvayda district'},
    {'id': 171, 'province_id': 12, 'name_uz': 'Dang‘ara tumani', 'name_cyrillic': 'Данғара тумани',
     'name_ru': 'Дангаринский район', 'name_en': 'Dang‘ara district'},
    {'id': 172, 'province_id': 12, 'name_uz': 'Yozyovon tumani', 'name_cyrillic': 'Ёзёвон тумани',
     'name_ru': 'Язъяванский район', 'name_en': 'Yozyovon district'},
    {'id': 173, 'province_id': 12, 'name_uz': 'Quva tumani', 'name_cyrillic': 'Қува тумани',
     'name_ru': 'Кувинский район', 'name_en': 'Quva district'},
    {'id': 174, 'province_id': 12, 'name_uz': 'Quvasoy shahri', 'name_cyrillic': 'Қувасой шаҳри',
     'name_ru': 'город Кувасай', 'name_en': 'Quvasoy city'},
    {'id': 175, 'province_id': 12, 'name_uz': 'Qo‘qon shahri', 'name_cyrillic': 'Қўқон шаҳри',
     'name_ru': 'город Коканд', 'name_en': 'Qo‘qon city'},
    {'id': 176, 'province_id': 12, 'name_uz': 'Qo‘shtepa tumani', 'name_cyrillic': 'Қўштепа тумани',
     'name_ru': 'Куштепинский район', 'name_en': 'Qo‘shtepa district'},
    {'id': 177, 'province_id': 12, 'name_uz': 'Marg‘ilon shahri', 'name_cyrillic': 'Марғилон шаҳри',
     'name_ru': 'город Маргилан', 'name_en': 'Marg‘ilon city'},
    {'id': 178, 'province_id': 12, 'name_uz': 'Oltiariq tumani', 'name_cyrillic': 'Олтиариқ тумани',
     'name_ru': 'Алтыарыкский район', 'name_en': 'Oltiariq district'},
    {'id': 179, 'province_id': 12, 'name_uz': 'Rishton tumani', 'name_cyrillic': 'Риштон тумани',
     'name_ru': 'Риштанский район', 'name_en': 'Rishton district'},
    {'id': 180, 'province_id': 12, 'name_uz': 'So‘x tumani', 'name_cyrillic': 'Сўх тумани', 'name_ru': 'Сохский район',
     'name_en': 'So‘x district'},
    {'id': 181, 'province_id': 12, 'name_uz': 'Toshloq tumani', 'name_cyrillic': 'Тошлоқ тумани',
     'name_ru': 'Ташлакский район', 'name_en': 'Toshloq district'},
    {'id': 182, 'province_id': 12, 'name_uz': 'Uchko‘prik tumani', 'name_cyrillic': 'Учкўприк тумани',
     'name_ru': 'Учкуприкский район', 'name_en': 'Uchko‘prik district'},
    {'id': 183, 'province_id': 12, 'name_uz': 'O‘zbekiston tumani', 'name_cyrillic': 'Ўзбекистон тумани',
     'name_ru': 'Узбекистанский район', 'name_en': 'O‘zbekiston district'},
    {'id': 184, 'province_id': 12, 'name_uz': 'Farg‘ona tumani', 'name_cyrillic': 'Фарғона тумани',
     'name_ru': 'Ферганский район', 'name_en': 'Farg‘ona district'},
    {'id': 185, 'province_id': 12, 'name_uz': 'Farg‘ona shahri', 'name_cyrillic': 'Фарғона шаҳри',
     'name_ru': 'город Фергана', 'name_en': 'Farg‘ona city'},
    {'id': 186, 'province_id': 12, 'name_uz': 'Furqat tumani', 'name_cyrillic': 'Фурқат тумани',
     'name_ru': 'Фуркатский район', 'name_en': 'Furqat district'},
    {'id': 187, 'province_id': 13, 'name_uz': 'Bog‘ot tumani', 'name_cyrillic': 'Боғот тумани',
     'name_ru': 'Багатский район', 'name_en': 'Bog‘ot district'},
    {'id': 188, 'province_id': 13, 'name_uz': 'Gurlan tumani', 'name_cyrillic': 'Гурлан тумани',
     'name_ru': 'Гурленский район', 'name_en': 'Gurlan district'},
    {'id': 189, 'province_id': 13, 'name_uz': 'Qo‘shko‘pir tumani', 'name_cyrillic': 'Қўшкўпир тумани',
     'name_ru': 'Кошкупырский район', 'name_en': 'Qo‘shko‘pir district'},
    {'id': 190, 'province_id': 13, 'name_uz': 'Urganch tumani', 'name_cyrillic': 'Урганч тумани',
     'name_ru': 'Ургенчский район', 'name_en': 'Urganch district'},
    {'id': 191, 'province_id': 13, 'name_uz': 'Urganch shahri', 'name_cyrillic': 'Урганч шаҳри',
     'name_ru': 'город Ургенч', 'name_en': 'Urganch city'},
    {'id': 192, 'province_id': 13, 'name_uz': 'Xiva tumani', 'name_cyrillic': 'Хива тумани',
     'name_ru': 'Хивинский район', 'name_en': 'Xiva district'},
    {'id': 193, 'province_id': 13, 'name_uz': 'Xazarasp tumani', 'name_cyrillic': 'Хазарасп тумани',
     'name_ru': 'Хазараспский район', 'name_en': 'Xazarasp district'},
    {'id': 194, 'province_id': 13, 'name_uz': 'Xonqa tumani', 'name_cyrillic': 'Хонқа тумани',
     'name_ru': 'Ханкинский район', 'name_en': 'Xonqa district'},
    {'id': 195, 'province_id': 13, 'name_uz': 'Shavot tumani', 'name_cyrillic': 'Шавот тумани',
     'name_ru': 'Шаватский район', 'name_en': 'Shavot district'},
    {'id': 196, 'province_id': 13, 'name_uz': 'Yangiariq tumani', 'name_cyrillic': 'Янгиариқ тумани',
     'name_ru': 'Янгиарыкский район', 'name_en': 'Yangiariq district'},
    {'id': 197, 'province_id': 13, 'name_uz': 'Yangibozor tumani', 'name_cyrillic': 'Янгибозор тумани',
     'name_ru': 'Янгибазарский район', 'name_en': 'Yangibozor district'},
    {'id': 198, 'province_id': 14, 'name_uz': 'Bektimer tumani', 'name_cyrillic': 'Бектимер тумани',
     'name_ru': 'Бектемирский район', 'name_en': 'Bektimer district'},
    {'id': 199, 'province_id': 14, 'name_uz': 'Mirzo Ulug\'bek tumani', 'name_cyrillic': 'Мирзо-Улугбекский район',
     'name_ru': 'Мирзо-Улугбекский район', 'name_en': 'Mirzo Ulug\'bek district'},
    {'id': 200, 'province_id': 14, 'name_uz': 'Mirobod tumani', 'name_cyrillic': 'Миробод тумани',
     'name_ru': 'Мирабадский район', 'name_en': 'Mirobod district'},
    {'id': 201, 'province_id': 14, 'name_uz': 'Olmazor tumani', 'name_cyrillic': 'Олмазор тумани',
     'name_ru': 'Алмазарский район', 'name_en': 'Olmazor district'},
    {'id': 202, 'province_id': 14, 'name_uz': 'Sirg\'ali tumani', 'name_cyrillic': 'Сиргали тумани',
     'name_ru': 'Сергелийский район', 'name_en': 'Sirg\'ali district'},
    {'id': 203, 'province_id': 14, 'name_uz': 'Uchtepa tumani', 'name_cyrillic': 'Учтепа тумани',
     'name_ru': 'Учтепинский район', 'name_en': 'Uchtepa district'},
    {'id': 204, 'province_id': 14, 'name_uz': 'Yashnobod tumani', 'name_cyrillic': 'Яшнобод тумани',
     'name_ru': 'Яшнободский район', 'name_en': 'Yashnobod district'},
    {'id': 205, 'province_id': 14, 'name_uz': 'Chilonzor tumani', 'name_cyrillic': 'Чилонзор тумани',
     'name_ru': 'Чиланзарский район', 'name_en': 'Chilonzor district'},
    {'id': 206, 'province_id': 14, 'name_uz': 'Shayxontohur tumani', 'name_cyrillic': 'Шайхонтоҳур тумани',
     'name_ru': 'Шайхантахурский район', 'name_en': 'Shayxontohur district'},
    {'id': 207, 'province_id': 14, 'name_uz': 'Yunusobod tumani', 'name_cyrillic': 'Юнусобод тумани',
     'name_ru': 'Юнусабадский район', 'name_en': 'Yunusobod district'},
    {'id': 208, 'province_id': 14, 'name_uz': 'Yakkasaroy tumani', 'name_cyrillic': 'Яккасарой тумани',
     'name_ru': 'Яккасарайский район', 'name_en': 'Yakkasaroy district'},
    {'id': 209, 'province_id': 1, 'name_uz': 'Taxiatosh shahri', 'name_cyrillic': 'Тахиатош шаҳри',
     'name_ru': 'Тахиаташский район', 'name_en': 'Taxiatosh city'},
    {'id': 210, 'province_id': 2, 'name_uz': 'Asaka shahri', 'name_cyrillic': 'Асака шаҳри',
     'name_ru': 'Асакинский район', 'name_en': 'Asaka city'},
    {'id': 211, 'province_id': 9, 'name_uz': 'Bandixon tumani', 'name_cyrillic': 'Бандихон тумани',
     'name_ru': 'Бандиханский район', 'name_en': 'Bandixon district'},
    {'id': 212, 'province_id': 11, 'name_uz': 'Ohangaron shahri', 'name_cyrillic': 'Оҳангарон шаҳри',
     'name_ru': 'город Ахангаранский', 'name_en': 'Ohangaron city'},
    {'id': 213, 'province_id': 11, 'name_uz': 'Yangiyo‘l shahri', 'name_cyrillic': 'Янгийўл шаҳри',
     'name_ru': 'город Янгиюль', 'name_en': 'Yangiyo‘l city'},
    {'id': 215, 'province_id': 11, 'name_uz': 'Toshkent tumani', 'name_cyrillic': 'Тошкент тумани',
     'name_ru': 'Ташкентский район', 'name_en': 'Toshkent district'},
    {'id': 216, 'province_id': 13, 'name_uz': 'Xiva shahri', 'name_cyrillic': 'Хива шаҳри', 'name_ru': 'город Хива',
     'name_en': 'Xiva city'},
    {'id': 217, 'province_id': 13, 'name_uz': 'Do\'stlik shahri', 'name_cyrillic': 'Дўстлик шаҳри',
     'name_ru': 'город Дўстлик', 'name_en': 'Do\'stlik city'},
    {'id': 218, 'province_id': 14, 'name_uz': 'Yangihayot tumani', 'name_cyrillic': 'Янгиҳаёт тумани',
     'name_ru': 'Янгихаётский район', 'name_en': 'Yangihayot district'},
    {'id': 219, 'province_id': 13, 'name_uz': 'Tuproqqala tumani', 'name_cyrillic': 'Тупроққалъа тумани',
     'name_ru': 'Тироккальский район', 'name_en': 'Tuproqqala district'},
    {'id': 220, 'province_id': 7, 'name_uz': 'Davlatobod tumani', 'name_cyrillic': 'Давлатобод тумани',
     'name_ru': 'Давлатабадский район', 'name_en': 'Davlatobod district'},
    {'id': 221, 'province_id': 6, 'name_uz': 'G‘ozg‘on shahri', 'name_cyrillic': 'Ғозғон шаҳри',
     'name_ru': 'Город Гозган', 'name_en': 'G‘ozg‘on city'},
    {'id': 222, 'province_id': 1, 'name_uz': 'Bo‘zatov tumani', 'name_cyrillic': 'Бўзатов тумани',
     'name_ru': 'Бозатовский район', 'name_en': 'Bo‘zatov district'},
    {'id': 224, 'province_id': 5, 'name_uz': 'Shahrisabz shahri', 'name_cyrillic': 'Шаҳрисабз шаҳри',
     'name_ru': 'Город Шахрисабз', 'name_en': 'Shahrisabz city'},
    {'id': 225, 'province_id': 5, 'name_uz': 'Ko‘kdala tumani', 'name_cyrillic': 'Кўкдала тумани',
     'name_ru': 'Кукдалинский район', 'name_en': 'Ko‘kdala district'}

]
